server:
  port: 8080
  context-path: /Hospital
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG
spring:
  jpa:
    database: MYSQL
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/hospital
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  messages:
    basename: i18n/messages, i18n/messages_zh
management:
  security:
    roles: ADMIN