package com.praveen.Hospital.web.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ModelAndView;

import com.praveen.Hospital.web.entity.UserInfo;
import com.praveen.Hospital.web.repository.UserInfoRepository;

@RestController
@RequestMapping("/user")
public class UserController {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private UserInfoRepository userInfoRepository;

	@RequestMapping(name="adduser",method = RequestMethod.GET)
	public ModelAndView adduser() {
		return new ModelAndView("adduser");
	}
	

	
	@RequestMapping(value = "saveuser",method = RequestMethod.POST)
	public ModelAndView saveUser(@ModelAttribute("userinfo") UserInfo userInfo,BindingResult result, ModelMap model) {
		System.out.println("===========================> "+userInfo);
		System.out.println("===>> "+userInfoRepository.findByUsername("hello"));
		
		userInfoRepository.save(userInfo);
		
		return new ModelAndView("usersuccess");
	}
}
